---
steps:
  - name: "Test"
    command: "bin/test"

  - name: ":secret: Upload"
    command: ".buildkite/bin/upload-secrets"

  - wait

  - name: ":suspect: Test plain-utils pull"
    command: "plain-utils pull payments-staging"
    branches: master

  - name: ":suspect: Test docker hub pull + push"
    command: "docker pull everydayhero/hello_world:latest && docker push everydayhero/hello_world:latest"
    branches: master
