---
env:
  BUILDKITE_S3_ACL: private

steps:
  - name: ":buildkite: Packer Queue"
    command: "bin/buildkite-stack packer BuildStack=$BUILD_STACK"
    agents:
      queue: buildkite
    env:
      TEMPLATE: packer-stack.yml
