---
steps:
  - name: ":terraform: Plan"
    command: ".buildkite/bin/plan"

  - name: ":terminal: Test"
    command: "bin/run-tests"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: app
      BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.test.yml

  - name: ":terraform: Format"
    command: ".buildkite/bin/check-format"

  - wait

  - name: ":terraform: Apply"
    command: ".buildkite/bin/apply"
    branches: master

  - wait

  - name: ":secret: Upload"
    command: ".buildkite/bin/upload-secrets"
    branches: master

  - wait

  - name: ":suspect: Test plain-utils pull"
    command: "plain-utils pull payments-staging"
    branches: master

  - name: ":suspect: Test docker hub pull + push"
    command: "docker pull everydayhero/hello_world:latest && docker push everydayhero/hello_world:latest"
    branches: master
