---
steps:
  - name: ":terraform: Plan"
    command: ".buildkite/bin/plan"
    agents:
      - queue=elastic

  - wait

  - name: ":terraform: Apply"
    command: ".buildkite/bin/apply"
    agents:
      - queue=elastic
    branches: master

  - wait

  - name: ":secret: Upload"
    command: ".buildkite/bin/upload-secrets"
    agents:
      - queue=elastic
    branches: master

  - wait

  - name: ":suspect: Test plain-utils pull"
    command: "plain-utils pull payments-staging"
    agents:
      - queue=elastic
    branches: master

  - name: ":suspect: Test quay.io pull + push"
    command: "docker pull quay.io/everydayhero/hello_world:latest && docker push quay.io/everydayhero/hello_world:latest"
    agents:
      - queue=elastic
    branches: master

  - name: ":suspect: Test docker hub pull + push"
    command: "docker pull everydayhero/hello_world:latest && docker push everydayhero/hello_world:latest"
    agents:
      - queue=elastic
    branches: master

  - wait

  - name: ":metal:"
    command: "echo 'Nice'"
    agents:
      - queue=elastic
