---
env:
  BUILDKITE_S3_ACL: private

steps:
  - name: ":terminal: Test"
    command: "bin/run-tests"
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: docker-compose.test.yml

  - wait

  - name: ":scroll: env"
    command: "bin/generate-env env && bin/upload-secret env"
    branches: master

  - name: ":scroll: bootstrap"
    command: "bin/upload-secret --public-read scripts/bootstrap"
    branches: master
    env:
      BUILDKITE_SECRETS_KEY: ""
      BUILDKITE_USE_KMS: false
