#!/bin/bash

set -eu -o pipefail

TERRAFORM_VERSION=0.9.11
TERRAFORM_SHA256=804d31cfa5fee5c2b1bff7816b64f0e26b1d766ac347c67091adccc2626e16f3

PACKER_VERSION=0.12.3
PACKER_SHA256=d11c7ff78f546abaced4fcc7828f59ba1346e88276326d234b7afed32c9578fe

download_from_hashicorp() {
  local app="$1"
  local version="$2"
  local dest="$3"

  wget -q "https://releases.hashicorp.com/${app}/${version}/${app}_${version}_linux_amd64.zip" -O "$dest"
}

checksum_file() {
  local file="$1"
  local sha="$2"

  echo "$sha $file" | sha256sum --check --strict
}

install_from_hashicorp() {
  local app="$1"
  local version="$2"
  local sha="$3"
  local file="/tmp/${app}.zip"

  echo "Installing ${app}..."

  download_from_hashicorp "$app" "$version" "$file"
  checksum_file "$file" "$sha"

  sudo unzip -o "$file" -d /usr/bin
  rm -f "$file"

  echo "Finished installing ${app}"
}

install_ansible() {
  echo "Installing ansible..."
  sudo yum -y groupinstall "Development Tools"
  sudo yum install -y gcc-c++ patch readline readline-devel libffi-devel openssl-devel
  sudo pip install --install-option="--install-scripts=/usr/bin" ansible boto cryptography
  echo "Finished installing ansible"
}

install_convox() {
  echo "Installing convox..."
  wget -q "https://convox.com/install/linux.zip" -O /tmp/convox.zip
  sudo unzip /tmp/convox.zip -d /usr/bin
  rm -f /tmp/convox.zip
  echo "Finished installing convox"
}

configure_packer() {
  cat <<EOF | sudo tee -a /etc/sudoers.d/packer
buildkite-agent ALL=(ALL) NOPASSWD: /bin/mount *
buildkite-agent ALL=(ALL) NOPASSWD:SETENV: /usr/local/bin/packer build *
EOF
  sudo chmod 440 /etc/sudoers.d/packer
}

configure_ssh() {
  mkdir -p ~/.ssh/cm
  chmod 0700 ~/.ssh

  cat <<EOT
cat <<SSH_CONFIG > ~/.ssh/config
Host bastion-* *.plain.edh.ro
  ForwardAgent yes
  TCPKeepAlive yes
  ServerAliveInterval 300
  StrictHostKeyChecking no
  ControlPath ~/.ssh/cm/%r@%h:%p
  ControlMaster auto
  ControlPersist 10m
  User deployer

Host bastion-production
  Hostname bastion.everydayhero.io
  Port 2020

Host bastion-staging
  Hostname bastion.everydayhero-staging.io
  Port 2020

Host production-*.plain.edh.ro
  ProxyCommand ssh -q bastion-production 'ncat \\\`echo %h | cut -f 1-1 -d.\\\` %p'

Host staging-*.plain.edh.ro
  ProxyCommand ssh -q bastion-staging 'ncat \\\`echo %h | cut -f 1-1 -d.\\\` %p'

Host github.com
  StrictHostKeyChecking no
SSH_CONFIG
EOT
}

install_ansible
install_from_hashicorp "terraform" $TERRAFORM_VERSION $TERRAFORM_SHA256
install_from_hashicorp "packer" $PACKER_VERSION $PACKER_SHA256
install_convox

configure_packer
configure_ssh

sudo yum install gettext
